/** @type {import("stylelint").Config} */
export default {
  extends: ["stylelint-config-standard"],
  rules: {
    "at-rule-no-unknown": [true, { ignoreAtRules: ["theme"] }],
    "custom-property-empty-line-before": null,
    "custom-property-pattern": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-empty-line-before": null,
    "declaration-property-value-no-unknown": [
      true,
      {
        propertiesSyntax: {
          width: "| <--spacing()>",
          height: "| <--spacing()>",
          margin: "| <--spacing()>",
          "margin-top": "| <--spacing()>",
          "margin-right": "| <--spacing()>",
          "margin-bottom": "| <--spacing()>",
          "margin-left": "| <--spacing()>",
          "margin-block": "| <--spacing()>",
          "margin-inline": "| <--spacing()>",
          "margin-block-start": "| <--spacing()>",
          "margin-block-end": "| <--spacing()>",
          "margin-inline-start": "| <--spacing()>",
          "margin-inline-end": "| <--spacing()>",
          padding: "| <--spacing()>",
          "padding-top": "| <--spacing()>",
          "padding-right": "| <--spacing()>",
          "padding-bottom": "| <--spacing()>",
          "padding-left": "| <--spacing()>",
          "padding-block": "| <--spacing()>",
          "padding-inline": "| <--spacing()>",
          "padding-block-start": "| <--spacing()>",
          "padding-block-end": "| <--spacing()>",
          "padding-inline-start": "| <--spacing()>",
          "padding-inline-end": "| <--spacing()>",
          gap: "| <--spacing()>",
          "background-size": "| <--spacing()>",
          "background-position":
            "| [ center | [ left | right ] [ <length-percentage> | <--spacing()> ]? ] && [ center | [ top | bottom ] [ <length-percentage> | <--spacing()> ]? ]",
        },
        typesSyntax: { "--spacing()": "--spacing( <number> )" },
      },
    ],
    "import-notation": null,
    "rule-empty-line-before": null,
  },
};
