env:
  commonjs: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
settings:
  react:
    version: "detect"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
rules:
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "react/react-in-jsx-scope": "off"
