name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: reviewdog/action-setup@v1
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn --silent lint:rdjson | reviewdog -f=rdjson -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
      - id: format
        run: |
          yarn format
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=${{ github.actor }}" -c "user.email=${{ github.actor }}@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
