name: CI
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: tuqulore/.github/setup@bfc3a44941a6d4499735fa48c913b51c15f9ca7b # main
      - run: pnpm -r lint --fix
      - uses: tuqulore/.github/format@bfc3a44941a6d4499735fa48c913b51c15f9ca7b # main
