name: CI
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: tuqulore/.github/setup@cc8a49114d24092c90de619edef3518534fb074e # main
      - run: pnpm -r --if-present build
      - run: pnpm -r lint --fix
      - run: pnpm -r --if-present test
      - uses: tuqulore/.github/format@cc8a49114d24092c90de619edef3518534fb074e # main
