name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm -r lint
      - id: format
        run: |
          pnpm format
          echo "RESULT=$(git diff --shortstat)" >> $GITHUB_OUTPUT
      - if: steps.format.outputs.RESULT != ''
        run: |
          git -c "user.name=${{ github.actor }}" -c "user.email=${{ github.actor }}@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
