name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: |
          yarn release --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
