name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - uses: tuqulore/.github/setup@main
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm release --yes
