name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: |
          yarn build
          yarn release
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
