name: Release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: next semantic version(s) value
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - uses: tuqulore/.github/setup@bfc3a44941a6d4499735fa48c913b51c15f9ca7b # main

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create release branch and bump version
        run: |
          git checkout -b release
          pnpm packages:bump-version ${{ inputs.semver }} --yes --no-git-tag-version
          VERSION=$(cat lerna.json | jq -r .version)
          git commit --all --message "chore(release): v${VERSION}"
          git push -f origin release

      - name: Create pull request
        run: |
          VERSION=$(cat lerna.json | jq -r .version)
          gh pr create \
            --base main \
            --title "chore(release): v${VERSION}" \
            --body "Release v${VERSION}"
        env:
          GH_TOKEN: ${{ github.token }}

      - if: failure()
        run: git push origin :release
