name: Release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: next semantic version(s) value
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - uses: tuqulore/.github/setup@main
      - uses: tuqulore/.github/configure-git@main
      - uses: tuqulore/.github/bump-and-pr@main
        with:
          branch: release
          bump-command: pnpm packages:bump-version ${{ inputs.semver }} --yes --no-git-tag-version
          version-command: jq -r .version lerna.json
          commit-prefix: chore(release)
          pr-body: Release v${VERSION}
          github-token: ${{ github.token }}

      - if: cancelled() || failure()
        run: git push origin :release
