name: Version Up
on:
  workflow_dispatch:
    inputs:
      semver:
        description: next semantic version(s) value
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfiles --non-interactive
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git branch --move release
          git push -f origin release
          PREV_VERSION="v$(cat lerna.json | jq -r .version)"
          yarn versionup ${{ github.event.inputs.semver }} --yes
          NEXT_VERSION="v$(cat lerna.json | jq -r .version)"
          git commit --all \
            --message="chore(release): ${NEXT_VERSION}" \
            --message="diff: https://github.com/tuqulore/jumpu-ui/compare/${PREV_VERSION}...${GITHUB_SHA}"
          git push origin release
          gh pr create --fill
        env:
          GH_TOKEN: ${{ github.token }}
      - if: ${{ failure() }}
        run: git push origin :release
